parameters:
  - name: ciTarget
    displayName: "CI target"
    type: string
    default: bazel.release

steps:
  - task: CacheBeta@1
    inputs:
      key: '"${{ parameters.ciTarget }}" | ./WORKSPACE | **/*.bzl'
      path: $(Build.StagingDirectory)/repository_cache

  - bash: |
      echo "disk space at beginning of build:"
      df -h
    displayName: "Check disk space at beginning"

  - bash: |
      sudo mkdir -p /etc/docker
      echo '{
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
      }' | sudo tee /etc/docker/daemon.json
      sudo service docker restart
    displayName: "Enable IPv6"

  - script: ci/run_envoy_docker.sh 'ci/do_ci.sh ${{ parameters.ciTarget }}'
    workingDirectory: $(Build.SourcesDirectory)
    env:
      ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
      ENVOY_RBE: "true"
      # Use https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_repository_cache_hardlinks
      # to save disk space.
      BAZEL_BUILD_EXTRA_OPTIONS: "--config=remote-ci --jobs=$(RbeJobs) --curses=no --experimental_repository_cache_hardlinks"
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)
    displayName: "Run CI script"

  - bash: |
      echo "disk space at end of build:"
      df -h
    displayName: "Check disk space at end"
    condition: always()

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/bazel-out/**/testlogs/**/test.xml"
      testRunTitle: "${{ parameters.ciTarget }}"
      searchFolder: $(Build.StagingDirectory)/tmp
    condition: always()

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.StagingDirectory)/envoy"
      artifactName: ${{ parameters.ciTarget }}
    condition: always()
